#!/bin/sh
unset LOCAL_BACKEND_API_KEY GH_TOKEN GITHUB_TOKEN GH_CONFIG_DIR ANTHROPIC_API_KEY OPENAI_API_KEY GEMINI_API_KEY GOOGLE_API_KEY BROWSER_USE_API_KEY
exec /opt/openhands-acp/node_modules/.bin/claude-agent-acp
